AUDIO_ENABLE      = no
RGBLIGHT_ENABLE   = yes
BACKLIGHT_ENABLE  = no
NO_SECRETS        = yes
BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
INDICATOR_LIGHTS  = no
MAKE_BOOTLOADER   = yes
RGBLIGHT_STARTUP_ANIMATION = yes

CUSTOM_UNICODE_ENABLE = no
CUSTOM_BOOTMAGIC_ENABLE = no
OS_DETECTION_ENABLE := no
DEFERRED_EXEC_ENABLE := no
