MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = yes
ENCODER_ENABLE = yes
# LTO_ENABLE = yes
OLED_ENABLE = yes

# build for arcadia
CONVERT_TO = promicro_rp2040
LTO_ENABLE = no