MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
# RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
ENCODER_ENABLE = yes
# LTO_ENABLE = yes
OLED_ENABLE = yes
ENCODER_MAP_ENABLE = yes

WPM_ENABLE = yes

# build for arcadia
CONVERT_TO = promicro_rp2040
LTO_ENABLE = no