// Copyright 2023 Christopher Courtney, aka Drashna Jael're  (@drashna) <drashna@live.com>
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define CIRQUE_PINNACLE_SPI_DIVISOR 8
#define CIRQUE_PINNACLE_SPI_CS_PIN POINTING_DEVICE_CS_PIN

#define CIRQUE_PINNACLE_TAP_ENABLE
#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE

#define OLED_DISPLAY_128X128

#define ENCODER_RESOLUTION 2
#define OLED_KEYLOGGER_LENGTH 9

#define RGB_MATRIX_CENTER { 112, 28 }

#define I2C1_CLOCK_SPEED  400000

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 750U

#define SERIAL_USART_SPEED 30000
#define OLED_UPDATE_PROCESS_LIMIT 2
#define SERIAL_DEBUG
