VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no

# RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
VIALRGB_ENABLE = yes

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

OLED_ENABLE = yes

WPM_ENABLE = yes
CAPS_WORD_ENABLE = yes
AUTO_SHIFT_ENABLE = yes

# build for arcadia
CONVERT_TO = promicro_rp2040
LTO_ENABLE = no

BOOTMAGIC_ENABLE = yes
