#pragma once

#define BOOTMAGIC_LITE_ROW 5
#define BOOTMAGIC_LITE_COLUMN 2

#define BOOTMAGIC_LITE_ROW_RIGHT 11
#define BOOTMAGIC_LITE_COLUMN_RIGHT 7

#define SPLIT_LED_STATE_ENABLE
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_TRANSACTION_IDS_USER RPC_ID_USER_KEYMAP_SYNC
